version: '3.9'

services:

  redis:
    image: redis:7
    container_name: otp-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: otp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: otpdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otp-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - ./app.log:/app/app.log

volumes:
  pgdata:
